import { describe, it, expect } from 'vitest';
import {
  getTextureSource,
  isBackgroundSample,
  shopIconKey,
  getArtSpriteKeys,
} from '../art.js';
import { getSpriteConfig } from '../sprites.js';
import { UPGRADES } from '../shop.js';

describe('getTextureSource', () => {
  it('uses the loaded PNG when a texture exists for the key', () => {
    const hasTexture = (key) => key === 'player_idle_0';
    expect(getTextureSource(hasTexture, 'player_idle_0')).toBe('png');
  });

  it('falls back to procedural generation when no PNG texture is loaded', () => {
    const hasTexture = () => false;
    expect(getTextureSource(hasTexture, 'player_idle_0')).toBe('procedural');
  });
});

describe('isBackgroundSample (chroma key decision)', () => {
  // A sampled background corner colour (the green screen the model produced).
  const ref = [150, 191, 99];

  it('removes pixels that are already transparent regardless of colour', () => {
    expect(isBackgroundSample(255, 0, 0, 0, ...ref)).toBe(true);
  });

  it('removes pixels close to the sampled background colour', () => {
    expect(isBackgroundSample(152, 188, 102, 255, ...ref)).toBe(true);
  });

  it('keeps a dark outline pixel far from the background', () => {
    expect(isBackgroundSample(10, 10, 10, 255, ...ref)).toBe(false);
  });

  it('keeps a bright sprite color far from the background', () => {
    expect(isBackgroundSample(235, 235, 230, 255, ...ref)).toBe(false);
  });

  it('keeps the muted character greens, which differ from the bright bg', () => {
    // player palette '#3a5a3a' = (58, 90, 58)
    expect(isBackgroundSample(58, 90, 58, 255, ...ref)).toBe(false);
  });

  it('keys grey-green and purple backgrounds against their own corner', () => {
    expect(isBackgroundSample(159, 160, 140, 255, 159, 160, 140)).toBe(true);
    expect(isBackgroundSample(153, 136, 156, 255, 153, 136, 156)).toBe(true);
  });
});

describe('shopIconKey', () => {
  it('maps every real shop upgrade to a distinct, stable icon texture key', () => {
    const keys = UPGRADES.map((u) => shopIconKey(u.id));
    expect(keys.every((k) => typeof k === 'string' && k.length > 0)).toBe(true);
    expect(new Set(keys).size).toBe(UPGRADES.length);
    expect(shopIconKey('battery')).toBe(shopIconKey('battery'));
  });

  it('returns null for an unknown upgrade id', () => {
    expect(shopIconKey('not_a_real_upgrade')).toBeNull();
  });
});

describe('art generation scope', () => {
  it('includes the AI-rendered flat objects that read correctly top-down', () => {
    const keys = getArtSpriteKeys();
    expect(keys).toContain('furniture_table');
    expect(keys).toContain('item_battery');
    expect(keys).toContain('shop_bg');
  });

  it('excludes micro-sprites that are intentionally kept procedural', () => {
    const keys = getArtSpriteKeys();
    expect(keys).not.toContain('bullet_pistol');
    expect(keys).not.toContain('item_copper_coin');
    expect(keys).not.toContain('enemyBullet');
  });

  it('excludes the procedural creatures and vertical furniture from the AI manifest', () => {
    // The image model reverts to front/3-4 views for anything with vertical
    // structure (wardrobes, couches), so these stay hand-authored top-down
    // pixel art instead of AI-generated PNGs. crawler/spitter are small radial
    // creatures that also stay procedural.
    const keys = getArtSpriteKeys();
    const handAuthored = [
      'crawler_idle_0', 'crawler_walk_0', 'crawler_walk_1',
      'spitter_idle_0', 'spitter_idle_1', 'spitter_walk_0', 'spitter_walk_1', 'spitter_attack_0',
      'furniture_armoire', 'furniture_couch', 'furniture_counter',
    ];
    for (const key of handAuthored) {
      expect(getSpriteConfig(key), `${key} must still exist as a sprite`).toBeDefined();
      expect(keys, `${key} should be procedural, not AI-generated`).not.toContain(key);
    }
  });

  it('keeps the directional player/zombie sprites out of the AI manifest', () => {
    // player/basic-zombie are 8-direction PNGs generated by
    // scripts/gen-character-directional.mjs and loaded by filename glob, NOT via
    // ART_MANIFEST -- so they must not appear in getArtSpriteKeys().
    const keys = getArtSpriteKeys();
    for (const key of ['player_down', 'player_right', 'enemy_down', 'enemy_up_right']) {
      expect(keys, `${key} is loaded by glob, not the manifest`).not.toContain(key);
    }
  });
});
